"""Constants for the EMU2 Modbus integration."""

from __future__ import annotations

DOMAIN = "emu2_modbus"
PLATFORMS = ["sensor"]

CONF_DATA_TYPE = "data_type"
CONF_DEVICE_CLASS = "device_class"
CONF_INPUT_TYPE = "input_type"
CONF_PRECISION = "precision"
CONF_SCALE = "scale"
CONF_SLAVE = "slave"
CONF_STATE_CLASS = "state_class"
CONF_SWAP = "swap"

DEFAULT_NAME = "EMU Professional II"
DEFAULT_PORT = 502
DEFAULT_TIMEOUT = 5.0
DEFAULT_SLAVE = 1

DEFAULT_SENSORS: list[dict[str, object]] = [
    {
        "key": "energy_import",
        "name": "EMU Wirkenergie Import",
        "address": 5999,
        "input_type": "holding",
        "data_type": "uint64",
        "scan_interval": 30,
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "energy_export",
        "name": "EMU Wirkenergie Export",
        "address": 6019,
        "input_type": "holding",
        "data_type": "uint64",
        "scan_interval": 30,
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "power_total",
        "name": "EMU Wirkleistung Gesamt",
        "address": 8999,
        "input_type": "holding",
        "data_type": "float32",
        "scan_interval": 5,
        "unit_of_measurement": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "power_l1",
        "name": "EMU Wirkleistung L1",
        "address": 9001,
        "input_type": "holding",
        "data_type": "float32",
        "scan_interval": 5,
        "unit_of_measurement": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "power_l2",
        "name": "EMU Wirkleistung L2",
        "address": 9003,
        "input_type": "holding",
        "data_type": "float32",
        "scan_interval": 5,
        "unit_of_measurement": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "power_l3",
        "name": "EMU Wirkleistung L3",
        "address": 9005,
        "input_type": "holding",
        "data_type": "float32",
        "scan_interval": 5,
        "unit_of_measurement": "kW",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "reactive_power_total",
        "name": "EMU Blindleistung Gesamt",
        "address": 9009,
        "input_type": "holding",
        "data_type": "float32",
        "scan_interval": 10,
        "unit_of_measurement": "kvar",
        "state_class": "measurement",
        "scale": 0.001,
        "precision": 3,
    },
    {
        "key": "current_l1",
        "name": "EMU Strom L1",
        "address": 9100,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 5,
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 3,
    },
    {
        "key": "current_l2",
        "name": "EMU Strom L2",
        "address": 9102,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 5,
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 3,
    },
    {
        "key": "current_l3",
        "name": "EMU Strom L3",
        "address": 9104,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 5,
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "precision": 3,
    },
    {
        "key": "voltage_l1",
        "name": "EMU Spannung L1-N",
        "address": 9198,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 10,
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "key": "voltage_l2",
        "name": "EMU Spannung L2-N",
        "address": 9200,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 10,
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "key": "voltage_l3",
        "name": "EMU Spannung L3-N",
        "address": 9202,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 10,
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "precision": 1,
    },
    {
        "key": "pf_l1",
        "name": "EMU Leistungsfaktor L1",
        "address": 9298,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 10,
        "state_class": "measurement",
        "precision": 3,
    },
    {
        "key": "pf_l2",
        "name": "EMU Leistungsfaktor L2",
        "address": 9300,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 10,
        "state_class": "measurement",
        "precision": 3,
    },
    {
        "key": "pf_l3",
        "name": "EMU Leistungsfaktor L3",
        "address": 9302,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 10,
        "state_class": "measurement",
        "precision": 3,
    },
    {
        "key": "frequency",
        "name": "EMU Netzfrequenz",
        "address": 9308,
        "input_type": "holding",
        "data_type": "float32",
        "swap": "word",
        "scan_interval": 30,
        "unit_of_measurement": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "precision": 3,
    },
]
